### ISSUE TITLE
Github Pages - Core Concepts not described and html semantics

### ISSUE THREAD

**Issue by schaetor** [diconium/ethereal-nexus#71]
Hello, 

I recognized by the link
https://diconium.github.io/ethereal-nexus/docs/introduction/#license

that the section "core concepts" looks a bit broken.
![etherial_nexus_core_concepts](https://github.com/diconium/ethereal-nexus/assets/59655739/b79a6f54-944e-4006-9f9f-a5ae6528e497)

The links do not have any descriptive text.

Then I also took a look on the semantics and recognized the following issues:

1. block links:
```
<li class="link-card astro-dohjnao5"> <a href="/ethereal-nexus/docs/dashboard" class="astro-dohjnao5"> <h2 class="astro-dohjnao5">  <span class="astro-dohjnao5">→</span> </h2> <p class="astro-dohjnao5">  </p> </a> </li>
```

The usage of "block" links is not recommended, because the semantic is not conveyed as is. 
The whole text is read out to the user as link description.

2. heading hierarchy:
the heading level inside this list is the same as around. I assume should be one level less. Anyway recommend to get rid of the block links.

3. list semantic:
the list elements are missing a wrapping element
https://html.spec.whatwg.org/#the-li-element
```
<div class="docs-grid-cols-2 mt-6"><li class="link-card astro-dohjnao5"> ... </li> </div>
```

**Comment by schaetor** [comment]
Hello, 


the issue is probably obsolete now, since a new layout/page structure was published?

**Comment by fgmadeira** [comment]
Yes the issue has driven a refactor on the layout of the pages! Thanks
