### ISSUE TITLE
"placholder" has no impact on Editor in CMS

### ISSUE THREAD

**Issue by schaetor** [diconium/ethereal-nexus#78]
Hello, 

I recognized the `placeholder` property in the dialog schema to be a bit misleading.
``` 
const dialogSchema = dialog({
  heading_text: text({
    label: 'Title',
    placeholder: 'Have any questions?',
  }),
})
```

## Expected expectation:
The `placeholder` would work as a placeholder, as we know it from html input elements and is shown as placeholder in the dialog for AEM for example.

## Current result:
The `placeholder` is used in the Ethereal dashboard as description.
![EN_Dashboard_preview](https://github.com/user-attachments/assets/504bcf57-e7e1-46a6-8819-1915f384d0d2)

As we can see, that leads to quite weird descriptions.

**Comment by lopesdasilva** [comment]
Placeholder is now implemented and can be tested on the version.
